<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Deactivate_Yes button</name>
   <tag></tag>
   <elementGuidId>6ffb0411-e151-47a5-82a3-dc2e0121e578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b35-ConfirmYes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'b35-ConfirmYes' and (text() = 'Yes' or . = 'Yes')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div/div/span[2]/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>558a04cb-812a-4627-8ac9-2e0c1ee932b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Primary</value>
      <webElementGuid>987dbc5d-ed5e-455c-9a2c-3dfb9ce2fc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0ea1165-3b35-4d14-a4e2-65245dc45df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b35-ConfirmYes</value>
      <webElementGuid>d4b65ce1-004b-4d74-a28e-588531581972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>cc26d5c0-2087-4f91-9cab-1f314ffdb26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b35-ConfirmYes&quot;)</value>
      <webElementGuid>db524f33-f368-45ad-a5ec-e781e9ace93a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b35-ConfirmYes']</value>
      <webElementGuid>1194f074-df3d-4f7d-a743-9797886fcf8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[1]</value>
      <webElementGuid>80df2b4e-02a1-438d-955d-8189a1d21a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to deactivate this privilege group?'])[1]/following::button[2]</value>
      <webElementGuid>c36724bd-d3de-40a7-98b4-73b3113ac418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>bfcbaff9-c957-48d6-8ace-c8e3015a36a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/button[2]</value>
      <webElementGuid>065fc8b9-1577-441f-9604-7892713d38f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b35-ConfirmYes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>630f147d-a00b-4d49-b16f-f46f7edfbea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
