<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_Status Checkbox</name>
   <tag></tag>
   <elementGuidId>e97de3d4-e89b-4c5a-a6d8-789634025de3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Checkbox_UserStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Checkbox_UserStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c15bd31-cdd7-40e2-b2f5-bad98ab2afef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1d1d0111-5ae8-4f65-8b20-b66641baf26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>96905f23-7dc9-43cc-a7cb-ce7e747ec127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Checkbox_UserStatus</value>
      <webElementGuid>fa032556-59dc-4d5d-a584-7a9345ec758b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Checkbox_UserStatus&quot;)</value>
      <webElementGuid>6bf7728e-dfd9-4ded-929f-3d7f287422cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Checkbox_UserStatus']</value>
      <webElementGuid>f386b9a1-bbab-49c0-b7f9-4561b98a4ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b25-Column2']/div/span/input</value>
      <webElementGuid>93e12a74-9f6b-43f3-85cf-e2ca3d9f8142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>e988246e-0407-4069-960f-512e9dce4dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Checkbox_UserStatus']</value>
      <webElementGuid>7184e92d-7991-43b1-bc87-13d7c6f17e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
