<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_Mobile Number field</name>
   <tag></tag>
   <elementGuidId>bdac4c28-bde6-4eb5-a7bb-b6ae7696b32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inp_Mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inp_Mobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2a4b8d8-668a-4ac3-9ebd-6351f3b90fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe48d3b2-2b75-41f1-9018-f342aba678fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ThemeGrid_Width9 ThemeGrid_MarginGutter</value>
      <webElementGuid>d63ab6ef-4477-4b29-9287-76636019326d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1b30e842-7af1-4e70-b843-cc4f30442ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inp_Mobile</value>
      <webElementGuid>787b7272-c925-41e3-9ed5-1961ea089444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inp_Mobile&quot;)</value>
      <webElementGuid>434214c4-ff19-496d-b483-06b4373f4e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inp_Mobile']</value>
      <webElementGuid>0c6eb871-1f9f-4179-bc9d-8e9305463fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b37-Column1']/div/span/input</value>
      <webElementGuid>b33abfc6-e001-4c74-a27a-51d7ef1eacca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/span/input</value>
      <webElementGuid>6cba38ff-3737-4ab1-a25e-5c9a829ba7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Inp_Mobile']</value>
      <webElementGuid>110fc7c2-2dec-45ac-9d4f-9ba9e42761f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
