<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_User status_Checkbox_Yes</name>
   <tag></tag>
   <elementGuidId>0a8638f0-2644-42de-9481-301e9c3da769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b41-ConfirmYes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b41-ConfirmYes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c287e1ae-87fa-4ba2-ae89-1f86d5a6e24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Primary</value>
      <webElementGuid>84fdf566-c71d-4763-8df7-47b6f2c52f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c939364-d30b-42bd-a052-47d7815da12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b41-ConfirmYes</value>
      <webElementGuid>09d7f07c-c473-45d5-868f-201fe1781147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>8a759f44-21c0-423e-812c-fa690d8c7d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b41-ConfirmYes&quot;)</value>
      <webElementGuid>9efb8279-a5b1-4d12-b469-a054d9a93bad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b41-ConfirmYes']</value>
      <webElementGuid>0fc139eb-8480-49cf-b141-99e79fae5933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[5]/following::button[1]</value>
      <webElementGuid>a9758024-cac8-48f3-8484-28bfff0102fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you deactivate the user, they will lose their access to the system, do you want to continue?'])[1]/following::button[2]</value>
      <webElementGuid>c6c4b77a-02f4-461a-a1d1-463e29e1c67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>45137a13-647f-43e8-b8bd-f93e6be1951b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/button[2]</value>
      <webElementGuid>912cf5fe-df4d-4e19-94a7-5d0606b17f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b41-ConfirmYes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>2a7c8d70-d485-4129-a879-30e5bce61f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
