<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_City_Select</name>
   <tag></tag>
   <elementGuidId>a69f6307-a16c-4ac4-9d02-9335e2ba0f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>xpath1651220597872</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;choices--b32-b2-DropdownSelect-item-choice-4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d255bdd2-0f75-4c14-934f-8d19be9e02fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1651220597872</value>
      <webElementGuid>a525982c-9f64-4be8-b8ae-a116fc71416b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
