<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Activate_Yes(fet automation)</name>
   <tag></tag>
   <elementGuidId>2ec2e4e1-b24b-4330-b23c-9a8050e9972c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b42-ConfirmYes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b42-ConfirmYes']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Yes' or . = 'Yes')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1079e35b-2668-4590-9466-71473900f239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Primary</value>
      <webElementGuid>ac668398-e29a-4381-9511-f96e7198d9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2ab05a8-acf1-4a50-80cb-0775779518aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b42-ConfirmYes</value>
      <webElementGuid>63879119-dfa9-4ec1-9ab3-50efafb8c607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>2899dc59-1ca3-4c4f-a546-691944005ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b42-ConfirmYes&quot;)</value>
      <webElementGuid>e38199ab-c33c-4ea3-9fe5-db2087ff90ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b42-ConfirmYes']</value>
      <webElementGuid>c9f1ed9a-fbfb-4df2-a451-69d56617aed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[5]/following::button[1]</value>
      <webElementGuid>1d6e6b6e-28ee-4135-8e4f-d2848abc7364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to activate this user?'])[1]/following::button[2]</value>
      <webElementGuid>c3ab257f-5b7f-434f-8d91-fc3c8416900c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/button[2]</value>
      <webElementGuid>037f836a-968f-4ac2-a556-7597934e2c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b42-ConfirmYes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>c4b5da53-076f-4acf-ad21-5771f638f4d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
