<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_Mobile Number field</name>
   <tag></tag>
   <elementGuidId>00364d2e-1fe0-4179-820d-88aead8beadb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inp_Mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inp_Mobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dad9d36-55db-44d4-bc67-ff332d10f890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdc33326-4b17-4f32-ae63-d1e4f8fe02b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ThemeGrid_Width9 ThemeGrid_MarginGutter</value>
      <webElementGuid>f9c89ec8-e958-4189-b668-bbbe9dcc5f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f670f851-66bc-4c11-834f-8f097f237e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inp_Mobile</value>
      <webElementGuid>e982e2ce-115d-42c7-9dc4-bf5910b274ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inp_Mobile&quot;)</value>
      <webElementGuid>bd6af469-1ffa-404e-ad2c-f96ea093882c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inp_Mobile']</value>
      <webElementGuid>b7e1251d-9834-43dd-aad7-8bdda2a64601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b37-Column1']/div/span/input</value>
      <webElementGuid>26ecfcf7-25f9-4689-811e-270b1765e10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/span/input</value>
      <webElementGuid>f6440721-5b2b-4753-8d1a-62840745fb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Inp_Mobile']</value>
      <webElementGuid>4d468160-8b4b-46d6-8871-0dffcd389d82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
