<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_Email</name>
   <tag></tag>
   <elementGuidId>966bc0d9-a8cc-48ed-860f-5b08a2dacc82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inp_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inp_Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d30190df-94a7-4896-ba8e-3b5848004310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>933b8ed2-56d7-4408-956d-94409ffdc976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>a5a8a8bd-aa53-4b62-b5fb-5b7450aa0ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8c9a434f-5b82-400d-b838-cb8ba8843c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1806a464-8e68-4345-968c-0dd6d254ae3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inp_Email</value>
      <webElementGuid>e397ff5f-adb3-48c6-9bd5-9c9c481282f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inp_Email&quot;)</value>
      <webElementGuid>5ffe77e8-95dd-4249-bc64-69331b638c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inp_Email']</value>
      <webElementGuid>c60183e9-9de8-4fe5-93eb-414800c003ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b27-Column1']/span/input</value>
      <webElementGuid>127406fc-64c7-47a1-a5db-09eb7049793c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/input</value>
      <webElementGuid>b94e2c44-5307-443f-8b43-9183574716ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'Inp_Email']</value>
      <webElementGuid>a5732446-2efb-4898-97f0-f0173d41bfca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
