<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_User Name</name>
   <tag></tag>
   <elementGuidId>9ec5e88d-aa23-4954-9a7b-8ab72a4cd0b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inp_UserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inp_UserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e281fcfe-9533-408c-86a9-cc76de956fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62b1cf14-be3a-4f26-bc87-07c01e94a644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>30022704-070f-40ed-987a-187d95f57e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e076998d-a341-4bc3-9f43-f361531d6bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91bf1984-42b6-4367-a6d5-33b1276917fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inp_UserName</value>
      <webElementGuid>36b06390-e4b0-4a3a-9481-e6d4600cc118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inp_UserName&quot;)</value>
      <webElementGuid>5fd5f0e5-7f5d-4595-8210-4806f57e9228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inp_UserName']</value>
      <webElementGuid>c6420338-637a-4821-a130-baf80d214cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b26-Column1']/span/input</value>
      <webElementGuid>b2289246-9304-4338-a39a-0f2884a6de1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>371f5d1a-d8e2-4d85-9904-9bba132e9909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Inp_UserName']</value>
      <webElementGuid>724bd06b-9eb4-4247-96ae-8164756fb2d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
