<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privilege Group Management</name>
   <tag></tag>
   <elementGuidId>9e44109b-b5b9-43a7-bc28-69f294ce2263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-l1-55_1-MenuItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-55_1-MenuItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>381d4b23-0a7e-4e28-84b7-9018decac99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelink</value>
      <webElementGuid>d7ab8511-ec5f-45cf-b5f8-6e2dc00483d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/FusionCenter/PrivilegeGroupManagement</value>
      <webElementGuid>816f2608-41fe-4f85-a282-9bb0174b4e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-55_1-MenuItem</value>
      <webElementGuid>79c28213-f548-4d07-99b3-1642537c426e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privilege Group Management</value>
      <webElementGuid>5ddfdcae-c7b1-41dc-84db-f7db6c970c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-55_1-MenuItem&quot;)</value>
      <webElementGuid>74ea4e47-2d6a-498c-9e49-7be29e5ef96e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-l1-55_1-MenuItem']</value>
      <webElementGuid>79b4c8a0-54a8-40c3-a27b-d2d85a177e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-PageLinks']/div/div/span[2]/div/a</value>
      <webElementGuid>8cf8cb5b-6215-4904-8ce3-21d3ee0c7015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>48d49f6f-bf34-4949-b5b9-45710b889221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Content (Press Enter)'])[1]/following::a[2]</value>
      <webElementGuid>db8de739-873a-4185-971b-d2fdd490641d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User &amp; Account Management'])[1]/preceding::a[1]</value>
      <webElementGuid>e363464f-b20c-43bb-8cab-547527f39a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/FusionCenter/PrivilegeGroupManagement')]</value>
      <webElementGuid>3cf6de30-6009-4fd9-9b8b-8c7d8702f735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>f1857c88-1128-48f2-a7bd-7ee2eea7987e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/FusionCenter/PrivilegeGroupManagement' and @id = 'b2-l1-55_1-MenuItem' and (text() = 'Privilege Group Management' or . = 'Privilege Group Management')]</value>
      <webElementGuid>176a0bb1-adb5-4945-831e-15b15987687f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
