<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PVM_Cancel</name>
   <tag></tag>
   <elementGuidId>7d052e3d-73f3-4ea5-a531-a6a674abbec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b20-b1-b1-PopupCancel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b20-b1-b1-PopupCancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7566f49f-d67e-4d45-8fb2-d831e997cf0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-radius-rounded</value>
      <webElementGuid>8199e905-dc88-47cb-bd15-53aeef3f005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>664b367a-a290-4002-a8bb-d4aea3e8fa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b20-b1-b1-PopupCancel</value>
      <webElementGuid>9e69b92b-fa0a-4f3f-98f0-d73f74d3ea3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>2ddab8e7-dccc-4fef-813f-ee7d0642f04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b20-b1-b1-PopupCancel&quot;)</value>
      <webElementGuid>bd968b0b-17fa-4180-8068-9653244c3065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b20-b1-b1-PopupCancel']</value>
      <webElementGuid>b71819ed-b13e-4ac6-aeb1-099dd4e4ac76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b20-b1-b1-Form1']/div[2]/button</value>
      <webElementGuid>bcbfd12d-e208-41c6-a7bb-e821b438ed2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the file name'])[1]/following::button[1]</value>
      <webElementGuid>ad4c5d30-95e6-459c-81cc-cefbec7e2245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b20-b1-b1-PopupCancel', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>d4e0bb6e-5281-4081-b2b8-5e4a87f5a939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[2]/preceding::button[1]</value>
      <webElementGuid>fc362488-dfdb-4c85-9894-7d845856e2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>01914d6e-ffd7-47ef-8b24-c949195426be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b20-b1-b1-PopupCancel' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>39cda033-9003-4cb5-994f-15022f5bd179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
