<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PVM_Download</name>
   <tag></tag>
   <elementGuidId>977fdc3e-4dba-4aea-8372-4f0eb8625aa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b20-b1-b1-PopupDownload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b20-b1-b1-PopupDownload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92f2c5c4-9cf4-4643-9f3d-59454b2d3354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Primary ThemeGrid_MarginGutter</value>
      <webElementGuid>16ebd454-5677-4d26-aca5-8d2c66ec546a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bb9bdc2c-1292-469f-b241-985e74de2d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b20-b1-b1-PopupDownload</value>
      <webElementGuid>65b6d1db-4385-4b8d-86e0-3e16850957c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>c5e4b70b-fd0a-4282-b868-c5a8ad5ee54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b20-b1-b1-PopupDownload&quot;)</value>
      <webElementGuid>acebdcbc-65df-4138-97a8-e4601e32f0ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b20-b1-b1-PopupDownload']</value>
      <webElementGuid>71b6ae11-bd12-47c4-8f6d-af8849d1c86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b20-b1-b1-Form1']/div[2]/button[2]</value>
      <webElementGuid>a338b3bb-aaf1-431f-9f92-45beb47a4d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>de6f8f33-d7f1-46a2-876f-5e75b0ac5355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the file name'])[1]/following::button[2]</value>
      <webElementGuid>7bcb912d-630b-4079-9331-d8ad21ccbeff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>25f9525e-2474-4490-aee3-70c217ce3c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'b20-b1-b1-PopupDownload' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>8ff93cf5-eb12-4780-9882-87f12b197323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
