<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PVM_File name field</name>
   <tag></tag>
   <elementGuidId>7cd9df4d-a522-40da-8e20-ac9afb28f7f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b20-b1-b1-Input_FileName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b20-b1-b1-Input_FileName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c4d0bb2-3e37-4341-b7f6-d96b8617dacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73ddff9c-283a-4271-b792-52d2d7d191b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control text-align-center OSFillParent</value>
      <webElementGuid>0c20d5a0-85aa-48e5-92a5-5641e5808987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg:filename</value>
      <webElementGuid>91eb0a44-582f-4a78-b749-7dba06bdace7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7333e664-a8e3-45ee-9238-0ee61e938d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>42c8f0ba-a1e0-404b-a28f-67d542302a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b20-b1-b1-Input_FileName</value>
      <webElementGuid>1fc1df93-8550-485c-8e11-e4145d0bf0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b20-b1-b1-Input_FileName&quot;)</value>
      <webElementGuid>eeab2119-9893-4601-b23b-eac5a77501e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b20-b1-b1-Input_FileName']</value>
      <webElementGuid>ec8918e7-06b4-4739-8272-0f7474929b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b20-b1-b1-Form1']/div/span/input</value>
      <webElementGuid>7f983702-51c0-4dc5-9af8-db0861932b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/span/input</value>
      <webElementGuid>946ccfa2-0635-4179-ad3c-0f3b6a612725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Eg:filename' and @id = 'b20-b1-b1-Input_FileName']</value>
      <webElementGuid>6c507b81-9e3e-480a-aaed-2958ea950255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
