<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Log-out button</name>
   <tag></tag>
   <elementGuidId>1c389bb7-5370-4bda-b42d-6133ed389a0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b3-b2-Items']/div[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.profile-items > a.validatelink > span.icon.margin-left-xs.validatelink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c7898ed-9405-4d43-85fd-d5e5f1340e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon margin-left-xs validatelink</value>
      <webElementGuid>744a2ee9-d922-475d-9945-9092c6048608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>d34d19f0-1349-4420-9243-e1bf62ee0443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b3-b2-Items&quot;)/div[@class=&quot;profile-items&quot;]/a[@class=&quot;validatelink&quot;]/span[@class=&quot;icon margin-left-xs validatelink&quot;]</value>
      <webElementGuid>9ecc11b8-c87b-4bc3-bca2-773b44a328bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b3-b2-Items']/div[3]/a/span</value>
      <webElementGuid>66acaa56-ac69-4a47-b50a-0ae738ada9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Login'])[1]/following::span[1]</value>
      <webElementGuid>3b3b0f00-f144-44c3-aa6d-5b1b0d8f7496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test2'])[1]/following::span[2]</value>
      <webElementGuid>48540c9e-08c4-467f-9b57-603750c4f0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::span[1]</value>
      <webElementGuid>348a9516-b7ce-4da8-83eb-5bf35c60fcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize dashboard'])[1]/preceding::span[2]</value>
      <webElementGuid>f9f36358-49da-46f6-a86c-b9662ca3acfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>96a82f5c-8ef6-4e08-8978-6b852f607918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>65d340c8-0bff-4a7b-9f55-a3a993b089ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>acef6536-71fa-4b23-964f-7e65f5800aae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
