<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password field</name>
   <tag></tag>
   <elementGuidId>b2c24c1a-0082-4093-8b2b-1cd44e41bccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_PasswordVal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_PasswordVal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53eb2ba2-667f-4fd1-94d0-de34cf0db869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3f4f91e1-4235-4bd9-9f20-31547426d6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control OSFillParent</value>
      <webElementGuid>63f32f9c-28e0-4c0f-b340-4702f5ae0eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>760a982e-a046-4b8f-a12a-f85352384a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_PasswordVal</value>
      <webElementGuid>f842e392-4433-4d3b-b78a-aec4ed54dbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_PasswordVal&quot;)</value>
      <webElementGuid>8e7ef659-18eb-4d79-8af8-299f4a267c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_PasswordVal']</value>
      <webElementGuid>939181c4-3398-44ef-9579-cb23b9800237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-Input']/span/input</value>
      <webElementGuid>b81b94d0-0791-45b6-8880-c22e8e208c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/input</value>
      <webElementGuid>ea9b0e81-d41a-4a15-b0db-beeb09820377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Input_PasswordVal']</value>
      <webElementGuid>ce3e34e7-69b2-48bf-85d7-21376adc3c5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
