<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privilege Group Management</name>
   <tag></tag>
   <elementGuidId>c0de9ef5-74d2-42b1-a36b-ed1fcc390138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-55_1-MenuItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-l1-55_1-MenuItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c78de592-ffe7-4c32-85b9-84560c4a5804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelink</value>
      <webElementGuid>7cd569ec-aa87-4bdd-8e82-200f7f646620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/FusionCenter/PrivilegeGroupManagement</value>
      <webElementGuid>2b395ba9-9090-4f6d-8f89-a75be511b68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-55_1-MenuItem</value>
      <webElementGuid>76a76a06-e657-4cf8-b52c-46f6ba5aa311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privilege Group Management</value>
      <webElementGuid>d6729f87-9abc-47c6-b9da-4e92f58d8957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-55_1-MenuItem&quot;)</value>
      <webElementGuid>6ad4cdf7-2b42-493f-aa81-2301f0908bc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-l1-55_1-MenuItem']</value>
      <webElementGuid>a48c652e-0dbf-4415-87af-2ddbe6dfa141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-PageLinks']/div/div/span[2]/div/a</value>
      <webElementGuid>86a38c02-5693-4fa1-8938-0fc582fd2a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>34bb818f-151c-408a-8250-86ad6270a80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Content (Press Enter)'])[1]/following::a[2]</value>
      <webElementGuid>0b8a6a99-c658-43bb-96c4-99c6f8bfdee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User &amp; Account Management'])[1]/preceding::a[1]</value>
      <webElementGuid>3a2453e6-43f2-4a1a-b3c7-0dc37b735af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/FusionCenter/PrivilegeGroupManagement')]</value>
      <webElementGuid>c5380023-9dd3-47d6-aa18-779a0dabc649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>bd55503a-9d94-4ac1-822c-669e002be8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/FusionCenter/PrivilegeGroupManagement' and @id = 'b2-l1-55_1-MenuItem' and (text() = 'Privilege Group Management' or . = 'Privilege Group Management')]</value>
      <webElementGuid>de561bbc-4a35-45ac-b48e-ab3c0d6894aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
