<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Activate button(fet automation)</name>
   <tag></tag>
   <elementGuidId>55086c6f-3f5f-44af-8d12-c4b6155efa10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l2_0-979_0-ActivateRecord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div[2]/div[4]/div[1]/table/tbody/tr[1]/td[1]/div/a[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'javascript:void(0);' and (text() = 'Activate' or . = 'Activate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4098e146-c9d9-4f4e-8040-067d49aea933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>margin-left-s</value>
      <webElementGuid>1ba20687-2b38-4d32-b175-b43924dc95b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>11030888-732c-4fd7-9d69-94012bdc9901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l2_0-979_0-ActivateRecord</value>
      <webElementGuid>4ec278aa-1157-4262-acf9-0d71fb49371d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activate</value>
      <webElementGuid>98ac0a42-cbce-477d-aba4-6496a0916220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l2_0-979_0-ActivateRecord&quot;)</value>
      <webElementGuid>b6de1b73-6b5b-4530-be18-fc2198d94693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='l2_0-979_0-ActivateRecord']</value>
      <webElementGuid>00279769-996b-47e2-9c76-e9744dc506b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='List']/div[4]/div/table/tbody/tr/td/div/a[3]</value>
      <webElementGuid>e137b1c1-4600-4103-9f0b-32e90bd599f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Activate')]</value>
      <webElementGuid>706ce3d5-ffd1-4d02-8e01-739ff625ea05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[2]/following::a[3]</value>
      <webElementGuid>50203de4-2663-485d-b6cb-44c5add1d3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective Date'])[2]/following::a[3]</value>
      <webElementGuid>dd96b548-e351-47a5-94c3-85301aef7758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fet Automation Test'])[1]/preceding::a[1]</value>
      <webElementGuid>a6e1831f-6b0c-4794-988c-726c3eede799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fet Automation Test'])[2]/preceding::a[1]</value>
      <webElementGuid>653750a0-ceb0-429c-b200-f6c4b57c6777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Activate']/parent::*</value>
      <webElementGuid>345135d9-007a-47d6-9102-0a72bcf4c45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>6c8f128e-e67f-43d7-b012-8f7e9c7beb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>30b8ef55-333f-4c26-ad98-41d08d2498d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'l2_0-979_0-ActivateRecord' and (text() = 'Activate' or . = 'Activate')]</value>
      <webElementGuid>e58d0e62-4563-4270-8d4e-e957bd7917d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
