<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Activate_No button</name>
   <tag></tag>
   <elementGuidId>01f01973-d00e-4325-9e88-9868bdc7c909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b37-ConfirmNo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'b37-ConfirmNo' and (text() = 'No' or . = 'No')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b37-ConfirmNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c53c7a8-5bd3-4b49-a2bc-20abdd7cafc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-radius-rounded</value>
      <webElementGuid>c51af2cc-2638-4ee3-8090-5385cdfd9834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f3463df-e054-4eef-987d-5f942b9ab89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b37-ConfirmNo</value>
      <webElementGuid>36a97629-f153-4fba-b497-f476f39e2cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>fe49ef37-2966-45ad-a286-688373c95895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b37-ConfirmNo&quot;)</value>
      <webElementGuid>b41f989a-7ff4-48ac-8a17-61db580a193a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b37-ConfirmNo']</value>
      <webElementGuid>c4f35eee-8c9f-4d7f-81d0-1e07749ab0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to activate this privilege group?'])[1]/following::button[1]</value>
      <webElementGuid>676aba60-3ae6-44e5-be31-eca40c0fdca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b37-ConfirmNo', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>46166bdb-37e9-4aa8-9b7b-2bf3b99c7570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::button[1]</value>
      <webElementGuid>63a09698-233e-4dc7-aff8-92e2e41e7b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No']/parent::*</value>
      <webElementGuid>768e2fb4-155a-404c-b050-d61387f51ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/button</value>
      <webElementGuid>6687c92a-b37b-436a-b8dd-47fbe24d22ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b37-ConfirmNo' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>2874fec0-d74d-4329-b909-ab323e9efd0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
