<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add New User</name>
   <tag></tag>
   <elementGuidId>db51cbfe-9b14-45fc-aa32-c37351ff9092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddNewRecord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='AddNewRecord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc5a0476-6acc-435d-9c1e-b28695bb459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-small common-search</value>
      <webElementGuid>b0dba225-11d2-4ee4-b0ac-993062fa716e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36fa935e-67a9-4d9b-8e15-40de771c9fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddNewRecord</value>
      <webElementGuid>bbe30632-8049-4690-9037-6a69eb21723f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New User</value>
      <webElementGuid>d6b5de1c-8a83-46c6-a226-f7ec84f3bd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddNewRecord&quot;)</value>
      <webElementGuid>38c576e7-f828-46b0-9f04-97fde2246a02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='AddNewRecord']</value>
      <webElementGuid>0e5f6187-814c-4d87-b0b6-7e0635f1408e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-ButtonBar']/div/div[2]/button</value>
      <webElementGuid>2e2fa7e6-5dd4-4a04-8c54-be22d348cff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/following::button[1]</value>
      <webElementGuid>4d7008a4-e88d-4b9a-845c-c4d5c519bda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::button[2]</value>
      <webElementGuid>bdfeed32-1b92-4fc7-8407-040efb196d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User and Account Management'])[2]/preceding::button[1]</value>
      <webElementGuid>d1f082f4-886a-46d2-bc27-60fb472ddeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::button[1]</value>
      <webElementGuid>917a8fa7-10f7-4a22-9443-01da78018536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add New User']/parent::*</value>
      <webElementGuid>4c30438d-e44f-4151-9a4e-826fc63b2559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b0df7e7d-4320-4d70-81da-5e3fdb0783c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'AddNewRecord' and (text() = 'Add New User' or . = 'Add New User')]</value>
      <webElementGuid>b2160dde-9a4b-4084-917b-d976d54bc8d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
