<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create User_Phone Number _Extension</name>
   <tag></tag>
   <elementGuidId>f9231387-9bcc-497c-a676-f2e5e554d553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inp_Extension</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inp_Extension']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2488dab-5d29-4d74-9045-67423a59bec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>740f2f6a-d9d7-429a-85a1-ee986ceb6fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>922034bb-634c-45a0-a075-cc283cf19d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>672fa38c-6d8f-4181-a404-38fe91c78ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inp_Extension</value>
      <webElementGuid>0fe57e0f-5fc8-4ad6-a53a-fe46aed0c99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inp_Extension&quot;)</value>
      <webElementGuid>d285adbe-9c46-49c6-b455-c9bb95ed11f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inp_Extension']</value>
      <webElementGuid>7d6a142a-6b8f-419b-b267-4217435f320e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b34-Column2']/span/input</value>
      <webElementGuid>48b1b4b7-e056-428c-b120-83adea3e7b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>55dc20f9-0142-4804-9571-1f8b80c8fbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Inp_Extension']</value>
      <webElementGuid>75b8174a-1ee6-49e4-809b-b04ca45d2d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
