<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create User_Mobile Number_Area Code</name>
   <tag></tag>
   <elementGuidId>73713574-8666-4601-afda-3fdac5122652</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown_MobileCountryCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown_MobileCountryCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8b4645a3-49f8-4171-b3c4-c5f99806de28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>96480765-a0b3-4c21-a023-90c358ada556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1eb0453c-2c09-44d3-8452-254dba474035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown_MobileCountryCode</value>
      <webElementGuid>4780979f-b9be-48e1-90d0-939f982f893d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+1</value>
      <webElementGuid>a03f0064-3b29-42b9-995d-be33e668c3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown_MobileCountryCode&quot;)</value>
      <webElementGuid>5a2177b5-0320-4b20-b611-b419d0d8284f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown_MobileCountryCode']</value>
      <webElementGuid>00aa5fee-a415-489e-b168-7a43109269cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown_MobileCountryCode-container']/select</value>
      <webElementGuid>b9d8e920-855f-442b-8b74-64d25a70748f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile #'])[1]/following::select[1]</value>
      <webElementGuid>b46d1bd1-fdb9-449a-b7db-e724e15dbdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ext.'])[1]/following::select[1]</value>
      <webElementGuid>4b22b8c8-89e7-4769-9878-f609db7edd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>27caeb66-c7d8-4665-887c-9ff57473e8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>02184dd7-aa46-4f92-a0f5-fee45e15b349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/select</value>
      <webElementGuid>016b69c4-c501-4ec1-8196-15397ed2f391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown_MobileCountryCode' and (text() = '+1' or . = '+1')]</value>
      <webElementGuid>9136a001-eb45-47f2-87e0-1d912306ab4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
