<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create User_User Name</name>
   <tag></tag>
   <elementGuidId>3f62fbf4-4670-4b98-aad8-a36f05947aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inp_UserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inp_UserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5f8bac8-f6c4-4f5d-9070-9b4452b53484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c57a731-cbdc-4bb5-b07e-5f649dcc0ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>566461e2-278a-48c3-9b31-ff07d1aab121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>79154f17-6fd1-4197-b693-fdd9ec8b64ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c430637-f786-42aa-ba1a-40cc68b1e36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inp_UserName</value>
      <webElementGuid>34d1e4cb-f7f0-45ca-bbb7-0ff4fc77e542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inp_UserName&quot;)</value>
      <webElementGuid>88f2eb71-962d-4dfd-9a4f-1868bb34ce51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inp_UserName']</value>
      <webElementGuid>64c83d17-b8e4-438d-8882-0e7e195cf170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b26-Column1']/span/input</value>
      <webElementGuid>1e5ccfa2-bd9e-4df5-ba2a-ff3b8d741f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>b7bbaf9b-abd6-4f52-8be4-6d75335fb7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Inp_UserName']</value>
      <webElementGuid>77244583-bb28-4b7a-af43-cba310f6f21d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
