<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create User_User Login Name</name>
   <tag></tag>
   <elementGuidId>bbac020d-7dd6-4291-8b67-d94b3d253ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inp_UserLoginName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inp_UserLoginName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac9900e7-b5ee-4840-9293-38aa6ca347ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7cc4cba-39fd-42f9-961d-b65a287cfddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>3a5f09f5-a163-4d7f-ab71-31577b7575ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1266e867-34d5-4a05-b38b-2651455b42e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eb4c75d3-e28a-4c55-a4cb-8abb2587a47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inp_UserLoginName</value>
      <webElementGuid>b9e17e42-b855-4c57-9ffa-d0f589a2076e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inp_UserLoginName&quot;)</value>
      <webElementGuid>9cc3495b-c25d-46f3-9dc9-290c31dffde9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inp_UserLoginName']</value>
      <webElementGuid>e81957ce-20f2-4a88-bed3-32e893dc97a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b25-Column1']/span/input</value>
      <webElementGuid>0aa5f7a1-370f-4d28-a903-e834783edf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>237b3290-6cac-4106-913e-023db80b345a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Inp_UserLoginName']</value>
      <webElementGuid>e8c7a739-cbf5-450f-9e9b-6e0e8812a2f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
