<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Deactivate_Yes</name>
   <tag></tag>
   <elementGuidId>e10c9394-52d1-4501-b8ca-62aa572d7cf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b41-ConfirmYes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b41-ConfirmYes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3658dc6-0604-48ab-8c11-f41655d2aac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Primary</value>
      <webElementGuid>b057ed16-16c1-45e1-a4d6-1d9015d90ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae04c9ff-6e41-4099-b51f-2ccd08a8c907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b41-ConfirmYes</value>
      <webElementGuid>94616304-ca2d-44ca-ad3e-9d10ee9ebc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>861f4931-5c28-495f-b30c-1d2fd3c1ddc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b41-ConfirmYes&quot;)</value>
      <webElementGuid>1c1becd4-3b4b-48a2-91be-a005a4a6884c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b41-ConfirmYes']</value>
      <webElementGuid>8ce54a38-b6f7-46de-bde5-a8bcaae791be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[5]/following::button[1]</value>
      <webElementGuid>a2784914-2015-464a-b77f-4affb6032fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you deactivate the user, they will lose their access to the system, do you want to continue?'])[1]/following::button[2]</value>
      <webElementGuid>1d5ffd98-b853-41cd-b3bf-c2e11dc26952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/button[2]</value>
      <webElementGuid>d31afd33-42e6-4603-b710-29e7cb41b6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b41-ConfirmYes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>f0dd5a61-ceed-4cc6-b95f-9ccf149fcc44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
