<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Deactivate(fet automation)</name>
   <tag></tag>
   <elementGuidId>15e9cfd5-70f8-440a-9e07-ed35e7d1ccf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l6_0-91_0-DeactivateRecord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='l6_0-91_0-DeactivateRecord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2eb73dcf-8a6e-40d4-888c-1b2b2c39de3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>2aadd89b-18da-47a4-9379-647522fa04e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l6_0-91_0-DeactivateRecord</value>
      <webElementGuid>65491265-68b2-47cf-9fc8-0f6894a746db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deactivate</value>
      <webElementGuid>e296c869-63e6-49e6-b114-6b2e921005ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l6_0-91_0-DeactivateRecord&quot;)</value>
      <webElementGuid>5e30e984-f6b7-42f4-b7a5-532baf7f0c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='l6_0-91_0-DeactivateRecord']</value>
      <webElementGuid>504cc43b-f596-4c25-805b-bc56c23dd06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l6_0-91_0-b20-Column2']/a</value>
      <webElementGuid>b6c6cd9b-e120-4097-ae35-e5c85c7bf96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Deactivate')]</value>
      <webElementGuid>f5a5292d-9cf5-474c-9a89-9c4b02e8775f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/following::a[2]</value>
      <webElementGuid>cdf21cb1-f04d-4fd9-bbed-52af5afeed28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fet automation'])[1]/preceding::a[1]</value>
      <webElementGuid>fac786de-205d-43d1-b489-071f4720ae4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fet automation'])[2]/preceding::a[1]</value>
      <webElementGuid>3212cc2d-b8d7-42f7-bfc3-de828769ce26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deactivate']/parent::*</value>
      <webElementGuid>6af5ab43-71a4-4a27-93db-caf4a9f868e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[8]</value>
      <webElementGuid>a2ddfb86-eea0-4ad5-8294-c963fe9b980f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>6458c425-7759-4cf3-8c91-39ab8b8535ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'l6_0-91_0-DeactivateRecord' and (text() = 'Deactivate' or . = 'Deactivate')]</value>
      <webElementGuid>c7666e92-cf4e-4fad-9863-4db75d721da2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
