<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Deactivate_No</name>
   <tag></tag>
   <elementGuidId>5302a33a-d33c-4e31-b92b-fa53c55b5839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b41-ConfirmNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b41-ConfirmNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce04d7e8-c91a-49ec-8827-c780048ebaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-radius-rounded</value>
      <webElementGuid>8b4f93f6-cc21-46d3-88b5-1d841eb17c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf03a9f6-45a5-4868-a052-45011265bae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b41-ConfirmNo</value>
      <webElementGuid>752cdc76-9e48-4b6c-a5be-d775a37f81be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>895df6a0-2c2a-4f07-b476-9de42472ff77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b41-ConfirmNo&quot;)</value>
      <webElementGuid>a75be651-2d01-4b31-b1b0-75aca43e8286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b41-ConfirmNo']</value>
      <webElementGuid>eb24777f-4eb3-4fd1-a0cc-c36dff541344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you deactivate the user, they will lose their access to the system, do you want to continue?'])[1]/following::button[1]</value>
      <webElementGuid>f09254b0-3138-4db3-a87e-238d9ef862f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b41-ConfirmNo', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>f68771b7-8064-4aa7-a1b2-9d993979832f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/preceding::button[1]</value>
      <webElementGuid>e230e1dc-d0da-4611-8dd7-10e15afa6e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/button</value>
      <webElementGuid>00c21595-900d-4856-8cd6-ce9a65590711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b41-ConfirmNo' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>d6b1419c-73ac-4e46-af6e-21f770078ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
