<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_User Group</name>
   <tag></tag>
   <elementGuidId>367c6a6a-f9ac-490b-833a-356683f4b721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.choices.is-focused.is-open > div.choices__inner > div.search--wrapper > input.choices__input.choices__input--cloned</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>defd0c20-7cde-4eeb-925d-1990fb966e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2e86c19-36c2-44ca-b977-a443c939d266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__input choices__input--cloned</value>
      <webElementGuid>b2b9c079-e349-446a-a4b0-fa4950ca727f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e91a347a-f832-485c-9e90-cf35d74deeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08e6c518-d968-4e4b-950c-49857de12476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9ca61ab2-f633-40ed-91f1-07701522c7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7067c071-e859-4619-866e-c34f91c87335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>136e4d17-57ba-4263-b8ab-47187fc3385d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>92448599-302d-4976-9595-1332b61bdc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d771135d-4afc-4fe2-ab7c-8ee7b009427f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>choices--b31-SelectableTags-item-choice-1</value>
      <webElementGuid>a4e0f876-99ee-4b99-afef-28d7d705d396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$b31&quot;)/div[@class=&quot;choices is-focused is-open&quot;]/div[@class=&quot;choices__inner&quot;]/div[@class=&quot;search--wrapper&quot;]/input[@class=&quot;choices__input choices__input--cloned&quot;]</value>
      <webElementGuid>6f06e772-63cb-43bf-bf95-dc362ee4b59d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>7be15f29-aca9-4eca-b1c0-6e0b15c4b526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b31']/div/div/div[2]/input</value>
      <webElementGuid>3c2a13d3-3fd0-457a-b762-ed8d106a6e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>951c0c37-17aa-4498-af84-be61ba26e795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @title = 'Search']</value>
      <webElementGuid>c61685fe-5370-4f81-b327-e4c8d90b1d57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
