<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verification_Inactive</name>
   <tag></tag>
   <elementGuidId>be371ba5-f6ac-4a66-9049-8e6de229b03d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.status-contact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='UserGrid']/tbody/tr/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>26b43df1-70a6-473a-a358-7df0d08538c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status-contact</value>
      <webElementGuid>49ad8e38-1631-4dbe-abf1-7bfc3282a45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-header</name>
      <type>Main</type>
      <value>User Status</value>
      <webElementGuid>e54d952f-4cbd-4fc7-81fc-b7c9b73e2c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>87069a8b-14ec-4042-a362-5fea405ac69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserGrid&quot;)/tbody[1]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;status-contact&quot;]</value>
      <webElementGuid>31109ba6-437d-49ef-b327-68c2d69fc077</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='UserGrid']/tbody/tr/td[6]</value>
      <webElementGuid>73c89cf2-a2da-42cd-af59-73a15a76ebc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin User Group'])[2]/following::td[1]</value>
      <webElementGuid>25ef5676-2322-484b-9803-4efdd7fe6e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Administrators'])[2]/following::td[2]</value>
      <webElementGuid>645ee025-4c69-4526-b2b1-f0c35dd6b31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unlocked'])[1]/preceding::td[1]</value>
      <webElementGuid>c164d745-b1e3-43d9-ac95-e65fc6901896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>cd7ad82e-f1b2-4935-9366-f14560eba3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Inactive' or . = 'Inactive')]</value>
      <webElementGuid>4209ad2e-15b0-4691-a886-c8c189be53e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
