<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privilege Group Management</name>
   <tag></tag>
   <elementGuidId>a12f5aa9-9afd-486a-9eb4-77b5dcf41750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-l1-55_1-MenuItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-55_1-MenuItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eef60aba-9bf4-470f-b8a1-b59f29cfbb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelink</value>
      <webElementGuid>af515338-ab67-47d2-a629-981da338078a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/FusionCenter/PrivilegeGroupManagement</value>
      <webElementGuid>7a4b3b96-2894-4f02-9dbd-8c149278866a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-55_1-MenuItem</value>
      <webElementGuid>c1c29980-8fea-4aed-9f8f-1c3a09e4e12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privilege Group Management</value>
      <webElementGuid>23749f5c-0c12-49a2-8fd5-4ffc9b8be7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-55_1-MenuItem&quot;)</value>
      <webElementGuid>5997dc51-4e2f-4db3-9c3f-b74c0df66bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-l1-55_1-MenuItem']</value>
      <webElementGuid>db6ff3eb-7097-471b-96dd-003edd1cbe7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-PageLinks']/div/div/span[2]/div/a</value>
      <webElementGuid>a6b74b38-9769-47e4-adcb-8d67a010a6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>ae75a625-93db-4c50-89ed-752d797809cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Content (Press Enter)'])[1]/following::a[2]</value>
      <webElementGuid>bd2807dd-bae9-4ba5-862a-4c7256d7c28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User &amp; Account Management'])[1]/preceding::a[1]</value>
      <webElementGuid>88f8a6e6-c13d-4ba9-9314-18a36ed43085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/FusionCenter/PrivilegeGroupManagement')]</value>
      <webElementGuid>8f137a68-8563-4d00-b457-e19d9ad743b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>44f3068c-ebc1-40d7-a305-d0c3cd8181f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/FusionCenter/PrivilegeGroupManagement' and @id = 'b2-l1-55_1-MenuItem' and (text() = 'Privilege Group Management' or . = 'Privilege Group Management')]</value>
      <webElementGuid>8217b005-9431-453d-937d-fd44fedad1d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
