<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PVM_File name field</name>
   <tag></tag>
   <elementGuidId>19acfcd0-01e5-4e8a-988e-9460af7e46b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b20-b1-b1-Input_FileName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b20-b1-b1-Input_FileName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9af3064-d8a3-4722-b54a-2f5b661da51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>130a60d4-40ad-42db-9e51-11667fe43b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control text-align-center OSFillParent</value>
      <webElementGuid>19087f10-7691-4699-9661-10b881afc29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg:filename</value>
      <webElementGuid>d0e0466c-92da-46d4-b8f4-52e219e6a886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3a67dec9-d8ab-41bc-a79c-9ebeb4fbb61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4d03fef8-e2d8-4f1e-8a35-bf6af191da52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b20-b1-b1-Input_FileName</value>
      <webElementGuid>712a2a7c-2f34-4d80-a7a0-fb4dea13c43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b20-b1-b1-Input_FileName&quot;)</value>
      <webElementGuid>5050230a-e0fe-425d-b245-2f9b9e7c9489</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b20-b1-b1-Input_FileName']</value>
      <webElementGuid>b1edd8d8-4c37-481e-a528-9e75b64310c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b20-b1-b1-Form1']/div/span/input</value>
      <webElementGuid>ab60ae75-553b-4c49-95b3-2d4e462bf9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/span/input</value>
      <webElementGuid>001f97ea-478a-4249-99fe-7a6f5dfacda9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Eg:filename' and @id = 'b20-b1-b1-Input_FileName']</value>
      <webElementGuid>5c580d3f-17f8-41bc-8d13-897edba5702a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
