<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PVM_Cancel</name>
   <tag></tag>
   <elementGuidId>1369a6ec-a524-4785-95ec-05ba483c9bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b20-b1-b1-PopupCancel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b20-b1-b1-PopupCancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbf7073c-fa87-479d-bb2b-3e872ffe7702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-radius-rounded</value>
      <webElementGuid>ea628b9a-2511-46c8-9428-cf76fad9d0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c2125d8-4559-4943-8521-41c303e840f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b20-b1-b1-PopupCancel</value>
      <webElementGuid>1d5e8aa7-44cc-4201-9ce3-8adc34d6883b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>b21a729c-dbaf-4637-869b-512bb621026e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b20-b1-b1-PopupCancel&quot;)</value>
      <webElementGuid>d1c254f0-416a-4425-8161-fafe08197649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b20-b1-b1-PopupCancel']</value>
      <webElementGuid>63559b91-bd30-40ff-9053-8247b9dfde17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b20-b1-b1-Form1']/div[2]/button</value>
      <webElementGuid>42cee638-c2af-43e4-99dd-c9160167ff44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the file name'])[1]/following::button[1]</value>
      <webElementGuid>3fa257ce-9382-48ef-a284-6b7a488a34c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b20-b1-b1-PopupCancel', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>a82d204a-39a4-474c-9cd1-813dd0569bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[2]/preceding::button[1]</value>
      <webElementGuid>bd96a17b-d4f2-412e-b612-889c2d4f36cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>a72eb430-5d0a-46fb-bbd8-e136c39c8a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b20-b1-b1-PopupCancel' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>78d44dbc-d10f-4bd7-9b04-570bd6420bd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
