<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PVM_XLS Download button</name>
   <tag></tag>
   <elementGuidId>60189204-c95d-4fd8-b67f-d07bfc01a788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='$b20']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.margin-left-base</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f07a4ae-77ad-4d19-b3c0-f446ee78a789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>margin-left-base</value>
      <webElementGuid>b04abab6-5a60-4f2f-bffa-0d871fcf9d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$b20&quot;)/div[@class=&quot;justify-center OSInline&quot;]/div[@class=&quot;download-format-custom&quot;]/div[@class=&quot;margin-left-base&quot;]</value>
      <webElementGuid>7b6706df-deb8-4759-bf7b-55be06b5493c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b20']/div/div/div[2]</value>
      <webElementGuid>8b88911f-4940-4771-956c-23c767e4947f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::div[1]</value>
      <webElementGuid>c26eb22a-f1bd-461a-a12b-e69ed8da8e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege Groups'])[1]/following::div[13]</value>
      <webElementGuid>48dab6f9-9226-4c4f-90e1-051c11c16f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::div[4]</value>
      <webElementGuid>e2b1fe1d-8b2b-4caa-9b65-75b4c1cc130f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege Group Name'])[2]/preceding::div[4]</value>
      <webElementGuid>d466bfba-2837-4a87-8a75-158de868a39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>ae79f319-108f-41af-b7e6-e47aaecd13b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
