<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create User_Privelege Group_Values Reader</name>
   <tag></tag>
   <elementGuidId>30423645-fdf6-4433-9ab8-1474ffbba2e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;choices--b29-SelectableTags-item-choice-7&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>9c926081-144e-4b38-9e96-1fc2a55bcb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1650612531561</value>
      <webElementGuid>771ab1f5-261c-46ab-a880-fbdd6d73b310</webElementGuid>
   </webElementProperties>
</WebElementEntity>
