<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create User_Phone Number field</name>
   <tag></tag>
   <elementGuidId>3ce2c203-4272-4a38-954c-930b067758a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Inp_Phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Inp_Phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a6af4f3-11f5-45b5-b720-051fd79403e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12bc8d5b-b676-4f21-899c-965196a744bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ThemeGrid_Width9 ThemeGrid_MarginGutter</value>
      <webElementGuid>bad02460-ee0a-448a-af1a-a8173b5cd5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>792d0381-e213-46bf-9843-2aeaa9f22344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Inp_Phone</value>
      <webElementGuid>49274b38-478b-40d6-96f6-bfc0ea217091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inp_Phone&quot;)</value>
      <webElementGuid>d94743d4-7611-4278-886d-cc77babf0b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Inp_Phone']</value>
      <webElementGuid>1a1d4cfe-b5fb-4319-89ad-d709190be6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b34-Column1']/div/span/input</value>
      <webElementGuid>4dc1b6a9-74bb-4b48-8e0c-938c9d41b5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>8b309e23-d9f9-41e2-98e9-997cd862ca54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Inp_Phone']</value>
      <webElementGuid>60cd3394-5623-4d7c-a2ae-b9ff06f9670f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
