<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create User_Phone Number_Area code</name>
   <tag></tag>
   <elementGuidId>f4dc4744-881e-49d9-be3c-c887e112c54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown_PhoneCountryCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Dropdown_PhoneCountryCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4eaecc1d-32d2-4dbd-bb23-e4015e7a5f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>eab27643-ccfb-4ea4-b164-bc77962125af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c0e5e9e8-065b-4207-922b-96d9c5809aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown_PhoneCountryCode</value>
      <webElementGuid>9672b043-a55c-46e7-a5ef-1a0ceb95836b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+1</value>
      <webElementGuid>6f10304b-3694-41ea-8bdf-991529f56aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown_PhoneCountryCode&quot;)</value>
      <webElementGuid>721ea160-675b-4358-b97a-7a1a86f44868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown_PhoneCountryCode']</value>
      <webElementGuid>9f7dde11-a2c2-4164-ad5e-a70c5ee15c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown_PhoneCountryCode-container']/select</value>
      <webElementGuid>12681dcd-b35f-41c6-b91f-58f343c47e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone #'])[1]/following::select[1]</value>
      <webElementGuid>f1e53bc0-8dc1-46ac-9705-4ab231c814da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[3]/following::select[1]</value>
      <webElementGuid>d7fbc712-75ae-4deb-bea9-0c33bbcca438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ext.'])[1]/preceding::select[1]</value>
      <webElementGuid>f64e25b3-cd6e-4fe2-b4a8-baf7a7fb89ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile #'])[1]/preceding::select[1]</value>
      <webElementGuid>76c88f7c-ac7a-4314-90ae-259e67f2d0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/div/select</value>
      <webElementGuid>ed4fd0ce-8d7e-4a59-a2f7-8c626faf024f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown_PhoneCountryCode' and (text() = '+1' or . = '+1')]</value>
      <webElementGuid>5863b747-fb9b-4da9-9891-df3c479d45dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
