<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create User_City_Alabaster</name>
   <tag></tag>
   <elementGuidId>432812c7-cafc-44e1-93ba-593ed6446c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;choices--b32-b2-DropdownSelect-item-choice-5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0026a137-c9d4-4cfe-8c94-44177d1fcff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1650612968297</value>
      <webElementGuid>441d8fb9-575a-488d-a284-ab2655d0d2b0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
