<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit button_fet automation</name>
   <tag></tag>
   <elementGuidId>2090520c-db84-43a3-ad16-2351483246ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div[2]/div[4]/table/tbody/tr[1]/td[1]/div/div[1]/div/div/div[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;l6_0-91_0-ViewEditRecord&quot;)[count(. | //*[@href = 'javascript:void(0);' and @id = 'l6_0-91_0-ViewEditRecord']) = count(//*[@href = 'javascript:void(0);' and @id = 'l6_0-91_0-ViewEditRecord'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l6_0-91_0-ViewEditRecord</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41c07733-39d6-4fda-b924-6126ee36d974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>31481e22-4129-4c85-887c-ad7ca4d58d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l6_0-91_0-ViewEditRecord</value>
      <webElementGuid>3e58915c-3e6b-49dd-bb1c-6a341e895dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l6_0-91_0-ViewEditRecord&quot;)</value>
      <webElementGuid>627a2980-7f60-43a1-a6b5-9ffafb182c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='l6_0-91_0-ViewEditRecord']</value>
      <webElementGuid>0cad8d30-6058-4faa-bf21-72d6fe3a1241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l6_0-91_0-b19-Column1']/a</value>
      <webElementGuid>890cce64-439e-4914-be3a-485f11d4f2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated By'])[1]/following::a[1]</value>
      <webElementGuid>7942912f-e220-41b2-ae1a-0e2feec2a455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/preceding::a[1]</value>
      <webElementGuid>8b7a23d5-6d1c-46c1-ab6b-b1a4d6de7840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivate'])[1]/preceding::a[3]</value>
      <webElementGuid>4c0816e5-9e9d-4ac6-aef7-181c8dce62c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[5]</value>
      <webElementGuid>c02a25fa-35a7-447b-8711-b641bab7be72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/div/a</value>
      <webElementGuid>9ec7e2c0-084d-4665-a229-b6834a442940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'l6_0-91_0-ViewEditRecord']</value>
      <webElementGuid>bd88a54b-792d-49de-90c2-6429aced8737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
