<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Locked icon</name>
   <tag></tag>
   <elementGuidId>39e99700-1e0e-4deb-b3f6-f43483d9a975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div[2]/div[4]/table/tbody/tr[1]/td[1]/div/div[2]/div/div/div[1]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-lock.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b9ad7ff6-4283-4517-abdd-64412a04b868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-lock fa-2x</value>
      <webElementGuid>56266960-aa9b-4ad3-a410-f9ad1ccb22a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l6_0-91_0-LockRecord&quot;)/i[@class=&quot;icon fa fa-lock fa-2x&quot;]</value>
      <webElementGuid>f7d70eb0-65f3-4bc7-a09c-00eb28c297f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='l6_0-91_0-LockRecord']/i</value>
      <webElementGuid>7456dc64-7029-4f54-b050-343cd5942424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/i</value>
      <webElementGuid>d6427f67-9d45-409a-b3c7-f0f68dc213c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
