<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lock_No</name>
   <tag></tag>
   <elementGuidId>e1c8c03a-d6cf-48ed-a4e4-0015b0801214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b48-ConfirmNo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'No' or . = 'No')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b48-ConfirmNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5b634f4-9d9b-49c7-ab47-e497ae102552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-radius-rounded</value>
      <webElementGuid>f9188bd8-b56f-4322-92fa-5910bd4c5e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c55f798c-6d3b-479d-aea6-b09fb9a7ae20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b48-ConfirmNo</value>
      <webElementGuid>29ef4895-a865-4acd-9014-47e879046b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>8d41d04f-ded3-4334-a875-afe53b7ef519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b48-ConfirmNo&quot;)</value>
      <webElementGuid>486bbe47-f967-445b-840b-26279b478f3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b48-ConfirmNo']</value>
      <webElementGuid>4e041414-baf2-486f-90fb-495daf9bdebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you lock the user, they will lose their access to the system, do you want to continue?'])[1]/following::button[1]</value>
      <webElementGuid>32ebca03-4e78-4fef-9cf7-38f0bac8eada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b48-ConfirmNo', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>dc7098aa-4661-4194-890d-cebf3a93dff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/preceding::button[1]</value>
      <webElementGuid>6e7e3a5e-eba1-4337-b8fb-3cfe50dfb2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/button</value>
      <webElementGuid>5fa10bb4-ffa6-4bc6-92e9-62cc9fc4dc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b48-ConfirmNo' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>2523ce30-a4e2-4270-a314-3c65df688b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
