<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Access Checkbox</name>
   <tag></tag>
   <elementGuidId>c7ca20bb-caa2-4b2f-82f6-e8048ed39b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Checkbox_UserAccessStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Checkbox_UserAccessStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2517bbab-092d-405c-978d-362960eae7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0452739d-e41d-43b7-bf22-de823d26a97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>df2dde27-db0b-4689-b5ed-9b26a8bc8baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Checkbox_UserAccessStatus</value>
      <webElementGuid>ba6d3172-063a-4a9f-ad89-3a68e0854839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Checkbox_UserAccessStatus&quot;)</value>
      <webElementGuid>2876e7a9-66ad-430a-a7f7-cfc3af112d55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Checkbox_UserAccessStatus']</value>
      <webElementGuid>3923119a-2c2e-4a1c-9b3a-06623d2b41f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b26-Column2']/div/span/input</value>
      <webElementGuid>f5131867-ae76-4159-b01a-fcc2d7643754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/span/input</value>
      <webElementGuid>cd2c79a1-3213-48b3-80aa-f8db1ffb4487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Checkbox_UserAccessStatus']</value>
      <webElementGuid>ab879180-42fa-4cac-84d0-1ad234abcc7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
