<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Account Management</name>
   <tag></tag>
   <elementGuidId>773f9ec6-6fa6-4ed9-83d9-13686f3a673c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-l1-59_2-MenuItem']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'validatelink' and @href = '/FusionCenter/UserandAccountManagement' and (text() = 'User &amp; Account Management' or . = 'User &amp; Account Management')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-59_2-MenuItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>296420cb-d7f8-4e53-ba59-55f8601c726e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelink</value>
      <webElementGuid>3130f8da-a6ce-480c-b108-6a1f25c3be61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/FusionCenter/UserandAccountManagement</value>
      <webElementGuid>067109a9-e8ea-4e9b-98bf-11b67cda4577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-59_2-MenuItem</value>
      <webElementGuid>28a6b9b8-f609-4fb7-8576-f6d81ee82b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User &amp; Account Management</value>
      <webElementGuid>66e58c5a-38b6-4ed8-aa28-0649e5e54e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-59_2-MenuItem&quot;)</value>
      <webElementGuid>1fd08499-fbb9-4d39-ab94-a07aa8e87b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-l1-59_2-MenuItem']</value>
      <webElementGuid>eede8ce2-f7c5-47cb-a164-dea1a821c3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-PageLinks']/div/div/span[3]/div/a</value>
      <webElementGuid>56e82120-16db-4a71-b089-a3bdd27b71fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege Group Management'])[1]/following::a[1]</value>
      <webElementGuid>3eccecb6-3191-4258-a642-2fa218e64f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[2]</value>
      <webElementGuid>55477994-2ec5-408d-be3b-b1f1887c4a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>e8943f8c-24b8-4a29-bdd7-123cf5cc20f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/FusionCenter/UserandAccountManagement')]</value>
      <webElementGuid>878d4150-5294-4d54-b438-366f707c40df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/a</value>
      <webElementGuid>9d0235af-096f-4400-8a28-8a92948187df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/FusionCenter/UserandAccountManagement' and @id = 'b2-l1-59_2-MenuItem' and (text() = 'User &amp; Account Management' or . = 'User &amp; Account Management')]</value>
      <webElementGuid>291ddd1e-b4b0-4db4-b30e-b38d7a4c505d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
