<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>City_Alabaster</name>
   <tag></tag>
   <elementGuidId>7c995150-c437-409d-922e-ec5bd9dd28b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choices--b8-b8-DropdownSelect-item-choice-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;choices--b8-b8-DropdownSelect-item-choice-5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82ead0ec-6ffd-42fb-b06a-f16e7e65b115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item needsclick choices__item--choice choices__item--selectable is-highlighted</value>
      <webElementGuid>eb4dbf5e-e899-4fca-9ee6-55fa4fd1afb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>27492bdd-c952-4144-a1b3-a8e927fbbbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8945e715-78e9-4796-97e3-cbfc70e8cc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choices--b8-b8-DropdownSelect-item-choice-1</value>
      <webElementGuid>327987ee-a0d6-4c87-b97c-f252b2a59709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>435f8cec-2ac9-44d5-b6df-789b25d6318d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>425e3f49-d000-44a5-8e67-422754d5bf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Alabaster
      </value>
      <webElementGuid>3fcf9a0d-2ec9-41f8-966f-406e7087c7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choices--b8-b8-DropdownSelect-item-choice-1&quot;)</value>
      <webElementGuid>813872f8-169f-4178-b865-ebc909a8bd02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='choices--b8-b8-DropdownSelect-item-choice-1']</value>
      <webElementGuid>a79df0a8-950f-4434-9db3-02ba3c7f22ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-city']/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>b898e5bb-46d2-4eec-a917-73eabe9ff0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/following::div[1]</value>
      <webElementGuid>e0030302-fdfc-430b-bfa4-f43dc8f704a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alabaster'])[2]/following::div[5]</value>
      <webElementGuid>914ff65a-1b23-468a-bd72-0e1fb26c1129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Albertville'])[1]/preceding::div[1]</value>
      <webElementGuid>c0b4fd7a-dee7-4cbc-a6b5-236ae2c81cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alexander'])[1]/preceding::div[2]</value>
      <webElementGuid>1e5a3ab8-67ac-4ab1-b7fb-18d741ac16f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>09af029a-4c04-42c0-b812-c53af0a06b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'choices--b8-b8-DropdownSelect-item-choice-1' and (text() = '
        Alabaster
      ' or . = '
        Alabaster
      ')]</value>
      <webElementGuid>581c79be-de08-4c35-a366-1a9941e0a645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
