<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>locked</name>
   <tag></tag>
   <elementGuidId>3b240768-c15d-41b6-bf5a-feecdd225f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Dropdown6&quot;]/option[2]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>80679c4d-2a8c-47a0-8f7f-96799cda3083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1650454370835</value>
      <webElementGuid>5e6e9887-80f2-4eac-a6de-65e27edbf77c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
