<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search result_Inactive</name>
   <tag></tag>
   <elementGuidId>9e1a42c4-cd2a-4fb5-8556-72cef718d71e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='UserGrid']/tbody/tr[5]/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>eda97a56-4454-4c99-ae46-f16696a96c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status-contact</value>
      <webElementGuid>a8eebac0-c351-4f1d-86dd-22c87dac1d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-header</name>
      <type>Main</type>
      <value>User Status</value>
      <webElementGuid>45580825-cfe6-46a4-b2b5-5f55e489eb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>9d13097f-75ec-475c-921d-13cba8e4cce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserGrid&quot;)/tbody[1]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;status-contact&quot;]</value>
      <webElementGuid>f7479f46-0e2e-496f-991b-49bc1c62698d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='UserGrid']/tbody/tr[5]/td[6]</value>
      <webElementGuid>66eed8eb-d1ad-43dc-a59f-65e01e1c32c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FetLocked'])[1]/following::td[3]</value>
      <webElementGuid>276fb69e-aa6c-4e4f-8a7d-f91f7b9632c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER STATUS LOCKED'])[1]/following::td[4]</value>
      <webElementGuid>ba125a41-b59f-4c77-88c9-731e387f6356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unlocked'])[6]/preceding::td[1]</value>
      <webElementGuid>5b1f8a35-df1a-45ce-b76b-ab5611dffdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]</value>
      <webElementGuid>9ccaf6db-a5d8-4c6f-b95e-c42bcb9afa66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Inactive' or . = 'Inactive')]</value>
      <webElementGuid>f3b8d972-994c-4206-a9ea-b0417665a88a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
