<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search result- anonymous</name>
   <tag></tag>
   <elementGuidId>31766a5b-4bda-4f52-bba8-66de1fa90660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.table-row.Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='UserGrid']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>932d4845-3b65-4c45-a59e-0a0b6f0b6332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-row Name</value>
      <webElementGuid>8a3bfce7-c6f4-4d25-8f2e-386e50bbc6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-header</name>
      <type>Main</type>
      <value>User Login Name</value>
      <webElementGuid>7caf38d0-d918-4e13-a4f9-5d910d19a7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>4f0925ae-ae2e-4480-9858-fee410ffaa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserGrid&quot;)/tbody[1]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;table-row Name&quot;]</value>
      <webElementGuid>a771af96-0957-4921-acd8-6efd90d71f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='UserGrid']/tbody/tr/td[2]</value>
      <webElementGuid>ba1d0870-61d3-481c-aaea-4ebda74f9f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivate'])[1]/following::td[1]</value>
      <webElementGuid>fb6b492b-d8e8-48dc-8130-282357df6218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/following::td[1]</value>
      <webElementGuid>b352394e-73c9-45fa-955b-384e036a402b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anon User'])[1]/preceding::td[1]</value>
      <webElementGuid>44b442c4-baab-4215-b9df-6870b697b55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>141eca0c-15d4-4eb6-8ad8-f840b7e0e051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'anonymous' or . = 'anonymous')]</value>
      <webElementGuid>6739f835-0a23-4506-947b-3ed29b83efd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
