<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>State_Alabama</name>
   <tag></tag>
   <elementGuidId>5469bfe7-2f54-43f0-bd9f-f613fbdfe628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;choices--b8-b9-DropdownSelect-item-choice-1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a1b75f15-ed84-4d4e-bd24-f34b38d96ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1650544789643</value>
      <webElementGuid>3b006c2d-e1af-4d14-a200-1df777b213ee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
