<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unlocked</name>
   <tag></tag>
   <elementGuidId>a7659f2e-6971-4cbb-a3f0-f1508edb5b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Dropdown6&quot;]/option[3]

</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f4de8cc9-7792-400d-8ea1-2a407a9e0e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1650454427859</value>
      <webElementGuid>d88110de-ec6c-4bcd-9e5e-74eb843be92d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
