<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User access status dropdown</name>
   <tag></tag>
   <elementGuidId>ade64740-960c-46e2-8327-34f6ef241940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Dropdown6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f044ee43-747a-4829-8314-f9c254ffad02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display form-control</value>
      <webElementGuid>54fab72f-a123-4457-a51f-2c78eb4a8276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a6781f4-19c2-463b-80bb-131d4e4adb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown6</value>
      <webElementGuid>a0148315-4c80-4f24-ab1b-1a3e3525bdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ItemLockedUnlocked</value>
      <webElementGuid>b0924f22-1e33-4e67-af5b-05def83e1b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown6&quot;)</value>
      <webElementGuid>9f4d0a95-838b-4191-9a9b-996f9043f550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown6']</value>
      <webElementGuid>3db5591d-8a90-432d-a56a-688ce280e9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown6-container']/select</value>
      <webElementGuid>ec831f23-f205-48dc-9ff1-4e0e145f1869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Access Status'])[2]/following::select[1]</value>
      <webElementGuid>c8695269-3168-4115-8809-3473a71d7526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Status'])[2]/following::select[2]</value>
      <webElementGuid>4d05c2d3-183a-4204-907e-c8c7cda69a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Require Password Change'])[1]/preceding::select[1]</value>
      <webElementGuid>92741184-d9de-44ff-b7e8-64dd2380a731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/preceding::select[2]</value>
      <webElementGuid>6c04fd4b-8233-47ba-ab99-69fcf957dfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>7bf83734-3b40-4135-9f6f-3d26035520b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown6' and (text() = 'Select ItemLockedUnlocked' or . = 'Select ItemLockedUnlocked')]</value>
      <webElementGuid>8f5f6876-7ae7-48c9-ac12-8bdfe03830f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
