<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Download button(enabled)</name>
   <tag></tag>
   <elementGuidId>327515a2-466f-46bc-a480-d017811c5441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b16-b1-b1-PopupDownload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b16-b1-b1-PopupDownload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fde2cc1-3ce1-4498-bb8c-b8b2031ed1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Primary ThemeGrid_MarginGutter</value>
      <webElementGuid>37947216-acca-477a-b297-4a682346bc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>39198631-2492-4ce4-a285-78ba4b6272c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b16-b1-b1-PopupDownload</value>
      <webElementGuid>dd54ec57-b9f7-4e85-b005-1c3dc3d13af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>61ea132b-f4f0-425b-bac8-d8ae1ca442eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b16-b1-b1-PopupDownload&quot;)</value>
      <webElementGuid>d4c6fffb-d7a3-45fb-8a5a-cf71324ade53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b16-b1-b1-PopupDownload']</value>
      <webElementGuid>14707024-c4cd-4dba-a426-32501b563b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b16-b1-b1-Form1']/div[2]/button[2]</value>
      <webElementGuid>9e97fab8-9f3b-4af8-8c6c-218723ba7de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>3152ea0d-4d3c-4c65-b0f9-d0d0318f6083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the file name'])[1]/following::button[2]</value>
      <webElementGuid>912b5723-fef6-4174-b367-7703bd89a936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button[2]</value>
      <webElementGuid>210700c7-22fd-49a7-8dee-f3a2886b1595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'b16-b1-b1-PopupDownload' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>474131e0-2616-4047-b4e1-39bb1158aa3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
