<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>File name field</name>
   <tag></tag>
   <elementGuidId>f4d3f94f-c4c7-4311-869c-3a5c71289cfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b16-b1-b1-Input_FileName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b16-b1-b1-Input_FileName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5187e56b-cbd0-4ab1-9156-881e99815ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c307556e-dd11-4339-a941-fa2632298c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control text-align-center OSFillParent</value>
      <webElementGuid>858391d2-49d5-45b6-bc57-384ff28b1cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg:filename</value>
      <webElementGuid>01f12d84-cb47-4656-8976-37c5ec3d491b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6bba81ee-3b24-4515-ba7b-ccc5f122c829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>437042cb-4eab-4eea-b815-5177697c8b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b16-b1-b1-Input_FileName</value>
      <webElementGuid>be29a39e-86f7-4126-8a22-a718fa14392c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b16-b1-b1-Input_FileName&quot;)</value>
      <webElementGuid>15ecf102-1b68-49ae-9457-a28b42aa8214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b16-b1-b1-Input_FileName']</value>
      <webElementGuid>7565eb12-b993-40a2-af71-421bde37db5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b16-b1-b1-Form1']/div/span/input</value>
      <webElementGuid>fba80302-a378-426d-b867-d7eb2c942980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/span/input</value>
      <webElementGuid>f33c7474-7cb1-45ef-8fc8-734f5378d899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Eg:filename' and @id = 'b16-b1-b1-Input_FileName']</value>
      <webElementGuid>fdf42bbc-8f77-4496-a1a4-53aaf4c07782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
