<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Account Management</name>
   <tag></tag>
   <elementGuidId>d73bbd05-b3e4-4d37-b98c-9ecebfa0a27a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-59_2-MenuItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-l1-59_2-MenuItem']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'validatelink' and @href = '/FusionCenter/UserandAccountManagement' and (text() = 'User &amp; Account Management' or . = 'User &amp; Account Management')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>127be14a-a5cc-4775-b337-d37f33035c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelink</value>
      <webElementGuid>847acb45-4fbf-4eac-be43-6dee1490bf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/FusionCenter/UserandAccountManagement</value>
      <webElementGuid>5e3e3612-73e7-4c0e-9ab0-6962bf9c47c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-59_2-MenuItem</value>
      <webElementGuid>f6eae5a8-647b-4c56-999c-b65629c2acac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User &amp; Account Management</value>
      <webElementGuid>955cce9a-2901-4e96-a665-7d561adc5de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-59_2-MenuItem&quot;)</value>
      <webElementGuid>e5cc7673-b8b6-4192-9ff9-1eaa7e2633e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-l1-59_2-MenuItem']</value>
      <webElementGuid>2002494b-fdc0-49e9-9573-e2b44ee74c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-PageLinks']/div/div/span[3]/div/a</value>
      <webElementGuid>5a08d542-c97b-4de5-8a8a-2ec8d4b67120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege Group Management'])[1]/following::a[1]</value>
      <webElementGuid>8ac4cfe9-bb59-4312-a01f-5294e87c0497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[2]</value>
      <webElementGuid>16390a1e-cb00-499c-af29-ae935496d0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>253fe59e-183a-4c7e-b2be-275723c6b7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/FusionCenter/UserandAccountManagement')]</value>
      <webElementGuid>7644a7db-28cd-4f94-ae0c-7b283d0927b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/a</value>
      <webElementGuid>77516475-36c5-48b2-9b12-a99eddd02910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/FusionCenter/UserandAccountManagement' and @id = 'b2-l1-59_2-MenuItem' and (text() = 'User &amp; Account Management' or . = 'User &amp; Account Management')]</value>
      <webElementGuid>72e68b0d-f313-4e8a-b45a-8036d9b85da8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
