<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table Header_Deactivate</name>
   <tag></tag>
   <elementGuidId>215a88ff-4154-4a2d-bd28-bed21feadcf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:void(0);' and (text() = 'Deactivate' or . = 'Deactivate')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='l6_0-909_0-DeactivateRecord']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l6_0-909_0-DeactivateRecord</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>433c9cd9-61bc-4908-bbb3-f45f1e509099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>f11877f6-d496-406f-9b1f-436494ab4f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l6_0-909_0-DeactivateRecord</value>
      <webElementGuid>c59aba07-d9ad-463e-98b5-8cb9e50dcddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deactivate</value>
      <webElementGuid>0631e961-ff49-4b70-8fe3-32dbcbc2d197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l6_0-909_0-DeactivateRecord&quot;)</value>
      <webElementGuid>9c0b82c0-d866-4b7c-b75d-e36263822e16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='l6_0-909_0-DeactivateRecord']</value>
      <webElementGuid>fcfc8224-c717-432d-9522-9f3ee04cab65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l6_0-909_0-b20-Column2']/a</value>
      <webElementGuid>adc5b505-472a-470c-b126-81d09c3896f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Deactivate')]</value>
      <webElementGuid>ec53d4fc-090a-40fb-bc2b-282bdbc349d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/following::a[2]</value>
      <webElementGuid>53117db8-edfe-45e2-86fb-4811283148b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fet4'])[1]/preceding::a[1]</value>
      <webElementGuid>12093018-53e5-423d-9269-a44611c66482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fet4'])[2]/preceding::a[1]</value>
      <webElementGuid>a686337f-007e-4bf8-8f36-b573a82f906b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deactivate']/parent::*</value>
      <webElementGuid>57dc3ce6-e0f8-4db8-8d0b-a398505192fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[9]</value>
      <webElementGuid>bdb679b2-78f1-4e16-9158-0f8eb5cb92a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>905f0ec0-2f40-4de1-b562-944e2381dee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'l6_0-909_0-DeactivateRecord' and (text() = 'Deactivate' or . = 'Deactivate')]</value>
      <webElementGuid>4d3048e4-15bb-4c5d-9569-ed6c58bb6532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
