<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table Header_Locked icon</name>
   <tag></tag>
   <elementGuidId>bc805055-b376-4442-9463-6d35cad7f913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l6_0-44_0-b20-Column1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'l6_0-44_0-b20-Column1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div[2]/div[4]/table/tbody/tr[1]/td[1]/div/div[2]/div/div/div[1]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>200d727c-8401-4d72-917e-c33e73bf65fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>4ffb6125-cfcc-490a-9ec5-40d71be3deee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l6_0-44_0-b20-Column1</value>
      <webElementGuid>cd2a8f6c-a716-49ab-9172-54c9e75732fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l6_0-44_0-b20-Column1&quot;)</value>
      <webElementGuid>3c3546d2-970c-4798-b6a1-1fc4dce1fd92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='l6_0-44_0-b20-Column1']</value>
      <webElementGuid>5f564dae-dba7-4952-812d-cdf26dd20f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l6_0-44_0-$b20']/div/div</value>
      <webElementGuid>5b6ecf19-bb52-458b-ae36-8b439d203135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/following::div[4]</value>
      <webElementGuid>60dd8ded-37b4-4897-bb01-ea36944883bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivate'])[1]/preceding::div[1]</value>
      <webElementGuid>e55845c2-5114-4377-a326-c400929ded18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fet4'])[1]/preceding::div[2]</value>
      <webElementGuid>3a61aaa5-766a-410c-864f-fd4870f7fed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div/div/div</value>
      <webElementGuid>c09e3d8b-2500-4515-b946-eda8565c7a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'l6_0-44_0-b20-Column1']</value>
      <webElementGuid>bb404fa1-3abc-4f59-b2c8-5f7d703dc45b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
