<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table Header_Reset Password</name>
   <tag></tag>
   <elementGuidId>749a0e82-bcea-4660-a50e-044ef9a5a4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:void(0);' and (text() = 'Reset Password' or . = 'Reset Password')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='l6_0-909_0-ResetPasswordLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l6_0-909_0-ResetPasswordLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e0efb0b-9ae0-452f-84dd-e2e450939791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>44e243a0-d513-4e08-800c-5cfa06f0709c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l6_0-909_0-ResetPasswordLink</value>
      <webElementGuid>36ad542b-d826-41c2-9a7e-9b5abac91744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset Password</value>
      <webElementGuid>a709d7ba-7c01-4e26-bc4f-4fc6dd8d006c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l6_0-909_0-ResetPasswordLink&quot;)</value>
      <webElementGuid>93bc23f7-a847-4691-bd59-e5a3a4e2e3fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='l6_0-909_0-ResetPasswordLink']</value>
      <webElementGuid>bc41a4b2-bbc9-4646-833a-ba80f3fa9795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l6_0-909_0-b19-Column2']/a</value>
      <webElementGuid>f2484958-f1e9-4ba7-a982-b29cda96f200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reset Password')]</value>
      <webElementGuid>bfc32633-7099-4a10-b31a-f5cbc402e749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated By'])[1]/following::a[2]</value>
      <webElementGuid>a0238b56-8a93-491c-8178-f60a71d0b921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivate'])[1]/preceding::a[2]</value>
      <webElementGuid>4913e0bd-f76e-4388-a88f-54a453951014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fet4'])[1]/preceding::a[3]</value>
      <webElementGuid>10213653-ef27-4edf-9e33-0507341ec096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset Password']/parent::*</value>
      <webElementGuid>4140b07e-bbe0-40f2-bacb-9c1fa9c51af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>e947123b-98da-4cb5-a7d6-5ed73e399b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>c3b787a4-a6c2-43bc-90b4-91a57d1596b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'l6_0-909_0-ResetPasswordLink' and (text() = 'Reset Password' or . = 'Reset Password')]</value>
      <webElementGuid>26779cf4-43be-402e-a0ee-bdce64d589c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
