<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Account Management</name>
   <tag></tag>
   <elementGuidId>4564af3d-2ad9-4ef8-afc1-7d1a675eb535</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-59_2-MenuItem</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'validatelink' and @href = '/FusionCenter/UserandAccountManagement' and (text() = 'User &amp; Account Management' or . = 'User &amp; Account Management')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-l1-59_2-MenuItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f7dd86f-ad4a-4de3-b861-e6b302128625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelink</value>
      <webElementGuid>2bd6a74b-6611-4eee-a9e5-2fb221070c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/FusionCenter/UserandAccountManagement</value>
      <webElementGuid>d8dfed20-2fed-4e59-8bfe-748a6254fff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-59_2-MenuItem</value>
      <webElementGuid>e3d415ae-45f9-4838-ba86-fd9a18085623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User &amp; Account Management</value>
      <webElementGuid>9a1d0790-09be-412d-b2d4-bfd48388d22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-59_2-MenuItem&quot;)</value>
      <webElementGuid>ea4ca7ef-2840-4f0b-8c73-b334b1ae14cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-l1-59_2-MenuItem']</value>
      <webElementGuid>12aaf7e6-eee3-43fb-aa91-4d6445803df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-PageLinks']/div/div/span[3]/div/a</value>
      <webElementGuid>88e6908f-fcae-4d6a-b603-77998e70518e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege Group Management'])[1]/following::a[1]</value>
      <webElementGuid>8caf863a-8136-4cae-9fde-d42929ec9204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[2]</value>
      <webElementGuid>7dfca4e3-9dfd-4817-b012-9251f8c22a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>62458d1c-cd50-4304-bfaf-236f706f5417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/FusionCenter/UserandAccountManagement')]</value>
      <webElementGuid>b92df0a7-ba22-48f7-a843-5c892827a9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/a</value>
      <webElementGuid>5030d603-afb7-4247-9ff3-9e87ee185a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/FusionCenter/UserandAccountManagement' and @id = 'b2-l1-59_2-MenuItem' and (text() = 'User &amp; Account Management' or . = 'User &amp; Account Management')]</value>
      <webElementGuid>92163a77-fe03-45bc-8d5a-c207d131645f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
